[package]
name = "goodfetch"
version = "0.1.0"
edition = "2024"

[dependencies]
include_dir = "0.7.4"
rustix = { version = "1.1.2", features = ["system"] } 
users = "0.11.0"

[profile.release]
strip = true
opt-level = "s"
lto = true
